# ---------------------------------------------------------------------------
# Self-hosted Gitea — infrastructure layer
#
# Terraform provisions the box and the cloud firewall. Everything that happens
# *inside* the box is Ansible's job (see ../ansible). The handoff between the two
# is the generated inventory file at the bottom of this file.
# ---------------------------------------------------------------------------

resource "hcloud_ssh_key" "admin" {
  name       = "${var.name}-admin"
  public_key = file(pathexpand(var.ssh_public_key_path))
}

# Cloud-level firewall. This is deliberately redundant with the UFW rules applied
# by the Ansible hardening role: the cloud firewall drops traffic before it
# reaches the host, UFW protects against a misconfigured cloud firewall. Both
# layers must agree, so keep this list and roles/hardening/defaults in sync.
resource "hcloud_firewall" "gitea" {
  name = "${var.name}-fw"

  rule {
    direction   = "in"
    protocol    = "tcp"
    port        = "22"
    source_ips  = var.admin_cidrs
    description = "SSH (admin)"
  }

  rule {
    direction   = "in"
    protocol    = "tcp"
    port        = "222"
    source_ips  = var.admin_cidrs
    description = "Gitea SSH (git clone over ssh)"
  }

  rule {
    direction   = "in"
    protocol    = "tcp"
    port        = "80"
    source_ips  = ["0.0.0.0/0", "::/0"]
    description = "HTTP (ACME challenge + redirect to HTTPS)"
  }

  rule {
    direction   = "in"
    protocol    = "tcp"
    port        = "443"
    source_ips  = ["0.0.0.0/0", "::/0"]
    description = "HTTPS"
  }

  rule {
    direction   = "in"
    protocol    = "icmp"
    source_ips  = ["0.0.0.0/0", "::/0"]
    description = "ICMP (ping / MTU discovery)"
  }
}

resource "hcloud_server" "gitea" {
  name         = var.name
  server_type  = var.server_type
  image        = var.image
  location     = var.location
  ssh_keys     = [hcloud_ssh_key.admin.id]
  firewall_ids = [hcloud_firewall.gitea.id]

  public_net {
    ipv4_enabled = true
    ipv6_enabled = true
  }

  labels = {
    project    = var.name
    managed_by = "terraform"
  }

  # The stack holds Gitea repositories and the Postgres volume. Deleting the
  # server destroys both. Remove this block only when you have verified that
  # scripts/backup.sh output is stored somewhere other than this host.
  lifecycle {
    prevent_destroy = true
  }
}

# ---------------------------------------------------------------------------
# Handoff to Ansible
# ---------------------------------------------------------------------------

resource "local_file" "ansible_inventory" {
  count = var.generate_ansible_inventory ? 1 : 0

  filename        = "${path.module}/../ansible/inventory/hosts.ini"
  file_permission = "0644"

  content = <<-EOT
    # Generated by Terraform — do not edit by hand.
    # Regenerate with: terraform apply
    [gitea]
    ${hcloud_server.gitea.ipv4_address}

    [gitea:vars]
    ansible_user=root
    ansible_ssh_private_key_file=${pathexpand(var.ssh_private_key_path)}
    ansible_python_interpreter=/usr/bin/python3
  EOT
}
