---
- name: reload sshd
  ansible.builtin.systemd:
    name: ssh
    state: reloaded

- name: restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted

- name: reload sysctl
  ansible.builtin.command: sysctl --system
  changed_when: false
